version: '3.8'

services:
  # 1. El Cartero (Mosquitto MQTT)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-1
    ports:
      - "1883:1883"
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - ./mosquitto.conf:/mosquitto-no-auth.conf

  # 2. El Gestor (Node-RED)
  nodered:
    image: nodered/node-red:latest
    container_name: nodered-1
    ports:
      - "1880:1880"
    depends_on:
      - mosquitto

  # 3. La Base de Datos (InfluxDB)
  influxdb:
    image: influxdb:1.8
    container_name: influxdb-1
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=pruebas_tuya

  # 4. El Visualizador (Grafana)
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-1
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana-storage: